name: rnap
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py27_0
  - astor=0.7.1=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports.weakref=1.0.post1=py27_0
  - backports_abc=0.5=py27_0
  - biopython=1.72=py27h04863e7_0
  - blas=1.0=mkl
  - bleach=3.1.0=py27_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py27_0
  - configparser=3.7.1=py27_0
  - cudatoolkit=9.2=0
  - cudnn=7.3.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py27_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py27_0
  - entrypoints=0.3=py27_0
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - funcsigs=1.0.2=py27_0
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - gast=0.2.2=py27_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.16.1=py27hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py27h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - ipywidgets=7.4.2=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27_0
  - jupyter=1.0.0=py27_7
  - jupyter_client=5.2.4=py27_0
  - jupyter_console=5.2.0=py27_1
  - jupyter_core=4.4.0=py27_0
  - keras=2.2.4=0
  - keras-applications=1.0.7=py_0
  - keras-base=2.2.4=py27_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - linecache2=1.0.0=py27_0
  - markdown=3.0.1=py27_0
  - markupsafe=1.1.0=py27h7b6447c_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py27h7dd41cf_0
  - mkl_random=1.0.1=py27h4414c95_1
  - mock=2.0.0=py27_0
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27_0
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.4=py27_0
  - numpy=1.15.4=py27h1d66e8a_0
  - numpy-base=1.15.4=py27h81de0dd_0
  - openssl=1.1.1a=h7b6447c_0
  - pandas=0.23.4=py27h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - pathlib2=2.3.3=py27_0
  - pbr=5.1.1=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pip=18.1=py27_0
  - prometheus_client=0.5.0=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - protobuf=3.6.1=py27he6710b0_0
  - ptyprocess=0.6.0=py27_0
  - pygments=2.3.1=py27_0
  - pyparsing=2.3.1=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.7.5=py27_0
  - pytz=2018.9=py27_0
  - pyyaml=3.13=py27h14c3975_0
  - pyzmq=17.1.2=py27he6710b0_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py27_0
  - readline=7.0=h7b6447c_5
  - scandir=1.9.0=py27h14c3975_0
  - scikit-learn=0.19.2=py27h4989274_0
  - scipy=1.1.0=py27hfa4b5c9_1
  - send2trash=1.5.0=py27_0
  - setuptools=40.6.3=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - tensorboard=1.12.2=py27he6710b0_0
  - tensorflow=1.12.0=gpu_py27h2a0f108_0
  - tensorflow-base=1.12.0=gpu_py27had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py27_1
  - terminado=0.8.1=py27_1
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27_0
  - unittest2=1.1.0=py27_0
  - wcwidth=0.1.7=py27_0
  - webencodings=0.5.1=py27_1
  - werkzeug=0.14.1=py27_0
  - wheel=0.32.3=py27_0
  - widgetsnbextension=3.4.2=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cloudpickle==0.8.0
    - dask==1.1.4
    - keras-vis==0.4.1
    - matplotlib-venn==0.11.5
    - networkx==2.2
    - pillow==5.4.1
    - pywavelets==1.0.2
    - scikit-image==0.14.2
    - setuptools-scm==3.3.3
    - toolz==0.9.0
    - weblogo==3.6.0
prefix: /home/alovse/local/miniconda3/envs/rnap

